### ISSUE TITLE
Not pip installable 

### ISSUE THREAD

**Issue by marius311** [carronj/planck_PR4_lensing#4]
Because the package itself is imported in its setup.py 

https://github.com/carronj/planck_PR4_lensing/blob/257580db053a42f8a30b724ea2873eca08242fb0/setup.py#L2

and the package needs `cobaya` to be imported, pip install doesnt actually work unless you manually install cobaya, and it doesnt work at all for anything that installs by building an egg (eg `pip install git+https://github.com/carronj/planck_PR4_lensing.git` doesnt work bc of this, also uv, poetry, etc...) 

The fix is simply to move that author/version out of the package somehow so you dont need to import it. Various ways you might like to do that so figured Id leave it up to you rather than submit a PR. Would be really convenient for using this package in various environments if this worked. Thanks!

**Comment by carronj** [comment]
Hi Marius, I have tweaked the setup.py, hopefully it works for you now ?

**Comment by marius311** [comment]
Confirm it works for me now, thanks for the quick fix!
